[FEAT] 피드 생성을 위한 입력 폼
fe11-part2-team8/openmind pull request #12
Opened 2024-10-25 11:55 UTC by Jiwoo11111

## 요약
메인 페이지에서 사용할 피드 생성을 위한 입력 폼

## 구현
- [ x ] 피드 생성
- [ x ] 입력 유효성 검사
- [ x ] 유효한 값일 경우 질문 받기 버튼 활성화
- [ x ] localStorage에 피드 id 저장

## 추가
- [ x ] 피드 생성 시 랜덤 프로필 생성
- [ x ] /assets/image에 프로필 이미지 추가하기

2024-10-25 14:05 UTC, neruu00 requested changes
고생하셨습니다!

2024-10-25 14:05 UTC, neruu00 commented on src/App.js
> +import FeedFrom from './components/FeedForm';
이 부분 오타 나신 거 같아요!

2024-10-25 14:05 UTC, neruu00 commented on src/App.js
> +        <FeedFrom></FeedFrom>
`props.children`이 필요한게 아니라면 이렇게는 어떤가요?

```js
<FeedForm />
```

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +function FeedForm() {
용도를 정확히 나타내는 `FeeaCreateForm`같은 이름은 어떠신가요?

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +  const profileImages = [
값이 변하지 않는 상수의 경우는 컨포넌트의 외부에 정의해야 리렌더링 시 불필요한 재정의를 막을 수 있습니다.

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +    setInputValue(e.target.value);
```js
e.target.value.trim()
```

.trim() 메서드를 사용해 보세요! 해당 메서드는 문자열의 양옆 공백을 제거해 줍니다. 네이버에서 로그인 할 때 지우님의 이메일 뒤에 띄어쓰기를 하나 넣더라도 잘 로그인이 되는 이유입니다.

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +      }
상위 브랜치로 PR할 때는 console.log는 제거하는 것이 좋습니다!

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +        console.log(`이미 존재하는 피드 ID: ${subjectId}`);
상위 브랜치로 PR할 때는 console.log는 제거하는 것이 좋습니다!

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +  );
값을 전송하는 폼일 경우 `<form>` 태그를 사용하는 것이 바람직합니다.

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +  ];
순수 js에서는 이 방식도 좋겠지만, react에서는 사용할 수 없습니다.

react는 빌드하는 과정에서 파일의 구조가 변경되기 때문에 이렇게 바로 경로를 넣으시면 분명 오류가 발생하게 될 것입니다.

대신 이런 방법은 어떠신가요?

```js
// /assets/datas/propfiles;
import profile_dog from "...":
import profile_cat from "...":
import profile_monkey from "...":

const PROFILES = {
  dog : profile_dog,
  cat : profile_cat,
  ...
}

export default PROFILES
```

위 처럼 따로 데이터 파일을 만들어 둔 후 import해서 사용하는 것입니다.

2024-10-25 14:05 UTC, neruu00 commented on src/components/FeedForm/index.jsx
> +        subjectId = await postSubject(inputValue, randomProfileImage);
API로 프로필 관련 정보를 서버로 보낼 수 없어서 이 방법은 어려울 거 같습니다.

대신 이런 방법은 어떨까요?

피드의 생성 시간에 따라 특정한 로직을 사용해 프로필의 번호를 부여하는 겁니다.

예를 들어
```js
const profileNum = (시 + 분 + 초) % 10;
const userProfile = PROFILES[profileNum]
```

2024-10-25 15:56 UTC, Jiwoo11111 commented on src/components/FeedForm/index.jsx
> +  const findSubjectByName = async (name) => {
꼼꼼한 리뷰 감사합니다!! 보내주신 내용 다 확인했고 수정했어용

근데 이 부분이 헷갈리는게 저는 메인에서 이름(혹은 닉네임)을 입력했을 때 저장된 데이터에 같은 값이 있으면 기존에 생성된 피드로 이동하고, 없으면 새로운 userID를 생성해서 새로운 피드를 만드는 흐름으로 이해하고 만들었던 건데 혹시 이게 아닐까요???
재현님이 말씀하신 대로 중복 검사를 하지 않고 새로운 피드를 생성하면 매번 새로운 userID가 생성 돼서 이후 답변이나 사용자 식별이 어려워질 거 같습니다..!

2024-10-25 15:57 UTC, Jiwoo11111 commented on src/components/FeedForm/index.jsx
> +        subjectId = await postSubject(inputValue, randomProfileImage);
위에 답변 보낸 거랑 이거 빼거 다 수정했습니다!!

2024-10-25 20:13 UTC, JUYOUNG0728 commented on src/components/FeedForm/index.jsx
> +      console.error('피드를 조회하는 중 오류가 발생했습니다:', error);
useAsync 만들어서 pr 올렸습니다
에러 메시지 부분 수정해주시면 될 거 같아용

2024-10-25 20:19 UTC, JUYOUNG0728 commented on src/components/FeedForm/index.jsx
> +  };
보면서 잠깐 든 생각인데 랜덤 프로필 말고 이미지 직접 고를 수 있게 하는 것도 좋을 거 같아용ㅋㅋㅋ 나중에 완성하고 시간 남으면 같이 이야기 해보시는 거 어때용

2024-10-25 20:23 UTC, JUYOUNG0728 approved these changes
중간중간에 설명 글 들어가 있어서 되게 잘 읽혔어요! 고생하셨습니다!

2024-10-26 05:59 UTC, Woolegend commented on src/components/FeedForm/index.jsx
> +  const findSubjectByName = async (name) => {
이 부분은 제가 실수 한 거 같습니다.

일단 이 부분은 그대로 두시고 나중에 팀회의를 통해 개선사항에 대해 이야기 나눠요!

2024-10-26 10:24 UTC, Jiwoo11111 commented on src/components/FeedForm/index.jsx
> +  };
오오 그거도 좋은 거 같아요!!! 그럼 일단 프로필 이미지를 볼 수 있는 기능을 구현해야 될 거 같긴한데... 나중에 다시 얘기해봐요 ㅎㅎ

2024-10-26 10:28 UTC, Jiwoo11111 commented on src/components/FeedForm/index.jsx
> +  const profileImages = [
프로필 이미지 부분 아침에 회의할 때 적어놓긴 했는데 지금 하려니까 막상 헷갈려서요 일단 기억 나는대로 수정하긴 했는데 맞는지 확인 부탁드려요!!

2024-10-27 14:32 UTC, Woolegend approved these changes
리뷰에 대해 적극적으로 고려해주셔서 감사합니다. 수고하셨습니다!

2024-10-27 14:32 UTC, Woolegend commented on src/assets/datas/profile/index.js
> +};
마지막으로 이 부분만 수정하면 될 거 같아요!
```js
const PROFILES = {
  profiles_bear_smile,
  profiles_cat_bee,
  profiles_cat_smile,
  profiles_dog_hone,
  profiles_dog_smile,
  profiles_hamster,
  profiles_music_band_bass,
  profiles_music_band_guitar,
  profiles_pig,
  profiles_rabbit_smile,
};

export default PROFILES;
```

2024-10-28 04:01 UTC, Jiwoo11111 commented on src/assets/datas/profile/index.js
> +};
넵 수정했습니다!

2024-10-28 08:07 UTC, merged