[FEAT, FIX, REFACTOR] API 로직 수정, 커스텀 훅 제작
fe11-part2-team8/openmind pull request #13
Opened 2024-10-25 19:46 UTC by JUYOUNG0728

## 요약
API 로직 수정, 커스텀 훅 제작

## 구현
- [x] 서버에서 에러 메시지 받아오기
- [x] 예외 처리 커스텀 훅 제작
- [x] data.id 대신 data 전체 반환
- [x] 필요한 query는 urlSearchParams으로 지정

## 추가
- [x]  jsdoc 사용
- [x] PATHS 객체 추가
- [x] url 오타 수정 및 상단 keeping 삭제
- [x] 함수 및 변수 이름 변경

2024-10-26 01:09 UTC, haksoo0918 reviewed
주석을 너무 이뿌게 다신거 같아요. 👍 
궁금한건 그냥 궁금한거라 서브젝트리스트 파라미터만 확인해주시면 될것 같습니다. 😄

2024-10-26 01:09 UTC, haksoo0918 commented on src/api.js
> +async function getSubjectList() {
모든 사람 아니고 일부의 서브젝트 리스트 입니다.
파라미터로 오프셋과 리미트가 필요합니다.

2024-10-26 01:09 UTC, haksoo0918 commented on src/hooks/useAsync.js
> +    }
궁금한게 2개 있습니다.
첫번째는 싱크함수의 결과값을 리턴하지 않고 데이터로 보내는 이유가 궁금하고,
두번째는 에러를 던지지 않고 메시지만 던지는 이유가 궁금합니다.

2024-10-26 01:59 UTC, Woolegend requested changes
고생 많으셨습니다!

2024-10-26 01:59 UTC, Woolegend commented on src/api.js
> +const PATH = {
path들을 담고 있는 객체는 PATHS라고 명명하는게 더 좋을 거 같습니다.

2024-10-26 01:59 UTC, Woolegend commented on src/hooks/useAsync.js
> +  return { loading, error, data, wrappedFunction };
data를 전달하는 방식도 좋은 방법이지만 만약 data의 가공이 필요한 경우 setter 함수가 없어 불편할 수 있습니다. 그래서 이 부분은 팀회의를 통해 이야기한 후 경정해야 할 거 같습니다.

2024-10-26 01:59 UTC, Woolegend commented on src/api.js
> +  return response.data.id;
`id`만 전달하는 거 보단 `data` 전체를 전달하는게 더 좋을 거 같습니다.

2024-10-26 01:59 UTC, Woolegend commented on src/api.js
> +  return response.data.id;
이 부분도 동일하게 data 전체를 반환하는게 더 좋을 거 같습니다.

2024-10-26 01:59 UTC, Woolegend commented on src/api.js
> +  return response.data.id;
아 혹시 id만 반환하시는 이유가 있으신가요?

2024-10-26 04:19 UTC, JUYOUNG0728 commented on src/hooks/useAsync.js
> +    }
1. 여기서 usestate로 data 값을 보내주면 함수를 리턴해서 ui를 구현하는 것보다 더 편하게 사용할 수 있다더라구요! 그래서 넣었습니당
2. 어제 멘토님께서 에러 메시지만 얘기해주셔서 이것만 넣으면 될 줄 알았는디 혹시 에러 객체도 필요할까용???

2024-10-26 04:19 UTC, JUYOUNG0728 commented on src/api.js
> +async function getSubjectList() {
넵 확인했습니다! 수정할게용

2024-10-26 04:20 UTC, JUYOUNG0728 commented on src/hooks/useAsync.js
> +  return { loading, error, data, wrappedFunction };
네 알겠습니다~! 그럼 일단 이 부분은 어떻게 둘까요?

2024-10-26 04:23 UTC, JUYOUNG0728 commented on src/api.js
> +  return response.data.id;
포스트할 땐 아이디 값만 필요할 줄 알고 편하게 사용할 수 있게 저렇게 해놨는데 생각해보니 상황에 따라 다른 값도 필요하겠네영 수정해놓을게요

2024-10-26 04:42 UTC, Woolegend commented on src/hooks/useAsync.js
> +  return { loading, error, data, wrappedFunction };
제 생각에는 데이터의 반환은 랩핑된 함수에서 이루어 지는게 좋을 거 같습니다.

```js
const wrappedFunction = async (...args) => {
    setLoading(true);
    setError(null);

    try {
      return response =  await asyncFunction(...args);
    } catch (err) {
      setError(err.message);
      return;
    } finally {
      setLoading(false);
    }
```

2024-10-26 10:25 UTC, JUYOUNG0728 commented on src/api.js
> +async function getSubjectList() {
수정했습니다 :) 확인 부탁드립니다.

2024-10-26 10:26 UTC, JUYOUNG0728 commented on src/hooks/useAsync.js
> +  return { loading, error, data, wrappedFunction };
모두 수정했습니다 :) 확인 부탁드립니다.

2024-10-26 16:03 UTC, Woolegend approved these changes

2024-10-27 02:11 UTC, haksoo0918 approved these changes
수고하셨습니다. 👍

2024-10-27 06:10 UTC, merged