[fix] 서브젝트 생성 시 로컬 스토리지에 id가 저장되지 않던 오류 수정 #25
fe11-part2-team8/openmind pull request #26
Opened 2024-10-28 08:49 UTC by Jiwoo11111

2024-10-28 09:50 UTC, Woolegend requested changes
고생하셨습니다. API 인수 부분만 수정해주시면 될 거 같아요!

2024-10-28 09:50 UTC, Woolegend commented on src/components/SubjectCreateForm/index.jsx
> +      const result = await postSubject(inputValue, randomProfileImage);
저희가 사용하는 피드 생성 API는 `name` 파라미터만 가지고 있어요.

그래서 `randomProfileImage`를 인수로 전달이 안 됩니다.

API를 사용하실 땐, 항상 사용법을 숙지해주세요!

```js
/**
 * 서브젝트 보내는 함수
 * @param {string} name - 닉네임
 * @returns {Promise<string>} - 생성된 서브젝트의 ID
 */
async function postSubject(name) {
  const data = {
    name,
    team: TEAM,
  };

  const response = await instance.post(`${PATHS.SUBJECT}`, data);
  return response.data;
}
```

2024-10-28 10:28 UTC, Jiwoo11111 commented on src/components/SubjectCreateForm/index.jsx
> +      const result = await postSubject(inputValue, randomProfileImage);
수정했습니다!!!

2024-10-28 15:40 UTC, Jiwoo11111 commented on src/components/SubjectCreateForm/index.jsx
> +      const result = await postSubject(inputValue, randomProfileImage);
혹시 여기 프로필 이미지 로직은 다 제거하고 이미 서브젝트 목록에 있는 이미지들로 쓰는 방식으로 해도 될까요??

2024-10-28 15:43 UTC, Woolegend commented on src/components/SubjectCreateForm/index.jsx
> +      const result = await postSubject(inputValue, randomProfileImage);
서버에 프로필 관련 데이터를 저장하는 방식이 아니라면 가능합니다!

2024-10-28 16:15 UTC, Jiwoo11111 commented on src/components/SubjectCreateForm/index.jsx
> +      const result = await postSubject(inputValue, randomProfileImage);
네! 그럼 이 컴포넌트는 프로필 이미지 관련 다 제거하거 다시 올리겠습니다

2024-10-29 05:25 UTC, haksoo0918 approved these changes
이뿐 이미지 삭제된게 아쉽네요.
수고하셨습니다. :)

2024-10-29 05:27 UTC, Woolegend approved these changes

2024-10-29 05:27 UTC, merged