[Feat] 질문 리스트 아이템 #18
fe11-part2-team8/openmind pull request #30
Opened 2024-10-29 07:48 UTC by Jiwoo11111

## 구현
- [x] 질문 잘 보여주기
- [x] 질문 작성 시간 기준 경과 표기
- [x] 질문 답변 여부 뱃지로 표기
- [x] 좋아요/싫어요 표기
- [x] 좋아요/싫어요 클릭 시 내역 반영
- [x] 답변이 있을 경우 해당 컴포넌트 렌더링
- [x] 사용자가 피드 주인일 경우 우상단에 ººº 버튼 렌더링

## 추가
- [x] dayjs 사용
- [ ] 더보기 버튼 (기능 추가하는 과정에서 해보는 거 어떨까요??)

## 설명
day js 설치했습니다!
답변 할 수 있는 기능 추가했습니다.
드롭박스에 있는 답변수정하기, 질문 삭제하기 기능도 추가했습니다.
코드에 스타일 코드 조금 있는데 그건 확인용이니까 디자인 할 때는 지워주세요.

## 파일 설명
QuestionAndAnswer : 질문과 해당 답변 표시
ReactionButton : 좋아요 싫어요 버튼 기능
Dropdown/index : 드롭다운 메뉴, 상태관리
Dropdown/EditAnswerForm : 답변 수정하는 기능

2024-10-29 17:20 UTC, JUYOUNG0728 commented on src/components/QuestionListItem/Dropdown/EditAnswerForm.jsx
> +
<form>으로 감싸주고 button type=submit으로 지정하면 나중에 유지보수도 쉽고 접근성도 좋다고 들었습니다!
추가적으로 빈 값일 땐 제출 버튼이 비활성화 되는 것도 어떨까요 ..?

2024-10-29 17:26 UTC, JUYOUNG0728 commented on src/components/QuestionListItem/QuestionAndAnswer.jsx
> +import { deleteQuestion, patchAnswer, postAnswer } from '../../api'; // 답변 수정 및 추가 API 불러오기
오늘 중으로 api 수정해서 올릴게요! 그 때 loading이나 error 사용해주시면 좋을 거 같습니당!

2024-10-29 17:32 UTC, JUYOUNG0728 commented on src/components/QuestionListItem/index.jsx
> +
여기도 훅으로 로딩 처리 하시면 좀 더 편하실 거에융

2024-10-29 17:33 UTC, JUYOUNG0728 approved these changes
코드 짱 기네요 ㄷㄷ 주석 덕분에 코드가 엄청 잘 읽혔어요! 고생 많으셨습니당!

2024-10-29 19:05 UTC, Woolegend requested changes
고생 많으셨습니다. 코드가 깔끔해서 무리 없이 리뷰할 수 있었습니다! 리뷰에 대한 내용은 모두 참고사항이니 필요하신 만큼 반영하시고, 말씀주시면 승인 드리겠습니다.

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/ReactionButton.jsx
> +export default ReactionButtons;
지금도 잘 만든 코드라서 참고용으로 남겨봤습니다.

개선된 코드의 목적은 두 가지 입니다.
1. 관리할 상태값 감축
2. 이벤트 위임을 활용해 핸들러 압축

`data-*`을 활용해 userReaction 상태값 대체

`.closet(element)` 가장 가까운 `element`를 반환합니다.

`hasAttribute()` 해당 요소가 특정 속성을 가지고 있으면 `true` 아니면 `false`를 반환합니다.

`setAttribute` 해당 요소에 속성을 설정합니다.

```js
const [reaction, setReaction] = useState({ like: initLike, dislike: initDislike });

  const handleClickReaction = async (e) => {
    if (e.target.hasAttribute('data-checked')) return;
    const btn = e.target.closet('button');
    const type = btn.dataset.type;

    try {
      setReaction((prev) => ({ ...prev, [type]: prev[type] + 1 }));
      e.target.setAttribute('data-checked', "");
      await postReaction(questionId, type);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div onClick={handleClickReaction}>
      <button data-type="like">
        좋아요: {reaction.like}
      </button>
      <button data-type="dislike">
        싫어요: {reaction.dislike}
      </button>
    </div>
  );
```

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/index.jsx
> +        const storedSubjectId = localStorage.getItem('subjectId');
로컬 스토리지에 사용하는 key를 변경하셨군요! 팀 회의 때 전파 부탁 드려요.

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/index.jsx
> +          />
모든 props를 개별적으로 전달하는 방식은 확실히 prop의 목적을 명확하게 알 수 있고, 불필요한 데이터가 전달되지 않는다는 장점이 있습니다. 하지만 전달할 prop가 너무 많을 경우 코드의 구조와 유지보수가 어려워 질 수 있습니다. 이 부분을 잘 고려해 props의 전달 방법을 선택해주세요

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/Dropdown/EditAnswerForm.jsx
> +export default AnswerEditor;
EditAnswerForm.jsx의 경로가 Dropdown 폴더 내부가 맞나요?

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/Dropdown/EditAnswerForm.jsx
> +function AnswerEditor({ answerId, questionId, initialContent, onSave, postAnswer }) {
파일의 이름은 EditAnswerForm인데 컴포넌트의 이름은 AnswerEditor라 일반적으로 좋은 관행은 아닙니다.

가능하시면 수정 부탁드립니다.

추가적으로 EditAnswerForm에서 Edit은 수정을 의미하는데 생성까지 도맡아 하는 컴포넌트의 이름으로는 적합하지 않아 보입니다.

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/Dropdown/EditAnswerForm.jsx
> +        await onSave(newContent, answerId);
onSave는 굳이 상위 컴포넌트에서 받아올 필요가 없을 거 같습니다.

answerEditor에서 answer에 대한 처리하는게 제가 볼 땐 바람직해 보입니다.

나중에 테스트나 유지보수를 생각해도 answer에 대한 기능인데 question에서 이를 다루면 불편할 거에요

2024-10-29 19:05 UTC, neruu00 commented on src/components/QuestionListItem/QuestionAndAnswer.jsx
> +      window.location.reload();
웹 페이지를 새로고침하면 편하긴 하지만, 불필요한 데이터까지 모두 불러오기 위해 많은 리소스가 소요될 거에요. 제가 추천드리는 방식은 변경된 부분만 새로 요청하는 것입니다.

2024-10-31 16:06 UTC, Woolegend approved these changes

2024-10-31 16:06 UTC, Woolegend commented on src/components/QuestionListItem/ReactionButton.jsx
> +    };
삼항 연산자 내부에 삼항 연산자를 넣는 방식은 코드 가독성을 떨어뜨리는 안 좋은 관습입니다. 

여러가지 조건을 검사해야 할 땐 차라리 `nested if` 혹은 다른 방법을 사용하는 것을 권장드립니다.

2024-10-31 16:06 UTC, Woolegend commented on src/components/QuestionListItem/ReactionButton.jsx
> +    }
참고 사항입니다.

localStorage는 삽입된 값이 항상 브라우저에 남아 있어 잘 관리해주어야 합니다. 그래서 여러 `key`를 사용하는 거 보다 하나의 `key`만 사용한 후 객체의 형태로 값을 저장하는 방법입니다.

```js
// reaction { like [ 8653, 8654, 8655, ... ], dislike : [ 8633, 8653, 8656, ... ] }

const log= JSON.parse(localStorage.getItem('reaction'));

log[type].push(questionId);

localStorage.setItem(reaction, log);
```

2024-10-31 16:06 UTC, merged