[FEAT, FIX] 개별 피드 페이지 구현, API 버그 수정, 유저플로우 및 시나리오 변경
fe11-part2-team8/openmind pull request #32
Opened 2024-10-29 18:33 UTC by JUYOUNG0728

## 요약
개별 피드 페이지 작업

## 구현
- [ ] 로컬 스토리지에 저장된 아이디로 본인 서브젝트인지 확인하고 맞으면 답변 작성, 아니면 질문 작성 버튼 활성화
- [ ] 각 서브젝트에 저장된 프로필 정보, 질문 개수 불러오기
- [ ] url 복사, 카톡/페북 공유 구현
- [ ] API에 이전에 남아있던 데이터 삭제

## 추가
- [ ] 우측 하단에 서브젝트로 이동하는 버튼 추가
- [ ] 기존 유저플로우와 시나리오를 사용자 편의에 맞게 변경

## 설명
1. 페북이랑 카톡은 배포 후 정상적으로 작동되는지 확인해봐야 할 거 같습니다.

2. 기존 : home에서 이름 입력 후 질문 받기 누르면 answer 페이지로 이동
    현재 : 
              - home에서 이름 입력 후 질문 받기 누르면 list로 이동
              - 서브젝트로 들어가면 조건부 렌더링 후 답변 작성하기 눌렀을 때 answer로 이동 (본인 서브젝트여야만 이동할 수 있어요)
              
3. 지우님꺼 질문 리스트 머지되면 나머지 작업도 들어가겠습니다.

4. 집중해서 하다보니 커밋을 자주 못 했네요 ..ㅎ;; 다음부터 신경쓰겠습니다!

2024-10-29 20:19 UTC, Woolegend approved these changes
매우 다양한 기능들을 사용하셨군요. 굉장합니다!

리뷰를 참고해 필요한 부분은 반영해주시고 말씀주시면 머지하겠습니다.

추가적인 부분인데 `app.js`에서 `<Link>` 컴포넌트가 정의된 후 사용되지 않아 빌드 오류가 발생했습니다. 이 부분은 fetch merge 후 `<Link>` 컴포넌트 선언부분을 지우거나 주석 처리 부탁드립니다.

2024-10-29 20:19 UTC, neruu00 commented on src/pages/PostPage.jsx
> +    };
이 부분은 컴포넌트 외부에 정의할 수 있나요?

외부에 정의할 수 있다면 useEffect가 작동할 때 마다 재정의 되는 것을 방지할 수 있을 것 같습니다.

2024-10-29 20:19 UTC, neruu00 commented on src/pages/PostPage.jsx
> +  };
해당 함수도 컴포넌트 외부에 정의한 후, id를 인수로 전달해도 될 거 같아요

2024-10-29 20:19 UTC, neruu00 commented on src/pages/PostPage.jsx
> +          console.log(questionError || subjectError);
console.log() 부분도 수정하실 때 제거 부탁드립니다.

2024-10-29 20:19 UTC, Woolegend commented on src/pages/PostPage.jsx
> +        setTotal(result.count);
질문의 개수만 따로 상태로 관리하기 보다, result 자체를 상태 값으로 관리하고, 하위 컴포넌트에 이 값을 props로 전달하는게 저희 코드 상에선 더 바람직해 보입니다. 해당 방식을 사용한다면 하위 컴포넌트에서 추가적인 요청을 보낼 필요가 없기에 더 효율적이고, 해당 페이지에서 사용되는 데이터가 일관적이기 때문에 상태관리가 더 용이합니다.

2024-10-29 20:19 UTC, Woolegend commented on src/pages/PostPage.module.css
> +}
키프레임 애니메이션을 사용하셨군요. 좋습니다!

2024-10-29 20:33 UTC, JUYOUNG0728 commented on src/pages/PostPage.jsx
> +    };
document.body.appendChild(script) 이 부분만 말씀하시는걸까용?

2024-10-29 20:38 UTC, JUYOUNG0728 commented on src/pages/PostPage.jsx
> +          console.log(questionError || subjectError);
헉 저건 나중에 오류 났을 때 콘솔 창에서 확인할 수 있게 하려고 넣었는데..! 빼는 게 좋을까요?

2024-10-29 20:42 UTC, Woolegend commented on src/pages/PostPage.jsx
> +          console.log(questionError || subjectError);
저 console.log 바로 뒤에 navigate와 return이 있는데, 혹시 값을 확인할 수 있나요?

2024-10-29 20:59 UTC, JUYOUNG0728 commented on src/pages/PostPage.jsx
> +          console.log(questionError || subjectError);
앗 알겠습니다! 일단 그럼 지워놓겠습니당

2024-10-30 05:49 UTC, JUYOUNG0728 commented on src/pages/PostPage.jsx
> +    };
이 부분 빼고 수정 완료되었습니다!
이건 바깥에 정의하니까 작동을 안 하더라구요ㅠ

2024-10-30 05:56 UTC, JUYOUNG0728 commented on src/pages/PostPage.jsx
> +    };
엌 해결했다! 수정해서 다시 올렸습니당ㅋㅋㅋ

2024-10-30 06:09 UTC, Woolegend commented
제가 볼 땐 문제 없어 보입니다

2024-10-30 06:54 UTC, haksoo0918 requested changes
수고하셨습니다. 👍 
라우터에는 페이지만 있으면 하는 바램과,
아이콘은 변경해서 사용해보시길 권장합니다.

2024-10-30 06:54 UTC, haksoo0918 commented on public/index.html
> +    <meta property="og:image" content="../src/assets/images/logo.svg" />
src폴더는 외부에 저렇게 접근이 안될꺼에요. /public 폴더에 이미지를 넣으시고 절대주소로 접근하시면 될꺼에요.
```html
<meta property="og:image" content="/images/logo.svg" />
```

2024-10-30 06:54 UTC, haksoo0918 commented on src/Main.jsx
> +          <Route index element={<SubjectCreateForm />} />
HomePage를 지우고 폼 컴포넌트를 넣으신 건가요?
HomePage에 넣으시던가 아니면 서브젝트 크래이트 페이지를 만드셔서 해당 컴포넌트를 넣는거는 어떠세요?

2024-10-30 06:54 UTC, haksoo0918 commented on src/assets/images/messages.png
이미 만들어진 이미지 파일이 있습니다.
assets/images/icon-message.svg 파일 이용하시면 됩니다.
fill color를 currentColor 로 넣어놨기 때문에
```jsx
import { ReactComponent as IconMessage } from '../assets/images/icon-message.svg';
// 생략 ...

<Iconmessage width="16" height="16" className="text-red-600" />
```
사이즈와 색상은 이런 형태로 넣어 사용하면 됩니다.

만약 svg 이미지가 어떤건지 확인하기 번거러우시면 vscode 확장에 svg 사용하시면 쉽게 미리보기 가능합니다.

2024-10-30 06:54 UTC, haksoo0918 commented on src/global.css
> +  }
`.btn-outline`으로 만둘어 둔게 있습니다. 확인 부탁 드립니다.

2024-10-30 06:54 UTC, haksoo0918 commented on src/pages/PostPage.jsx
> +        <div className="fixed bottom-[24px] right-[24px]">
tailwind에서 숫자로 사용하는 길이값은 4의 배수라고 생각하시면 쉽습니다.
`.bottom-6` 은 `.bottom-[24px]` 와 같습니다.

2024-10-30 06:55 UTC, JUYOUNG0728 commented on src/Main.jsx
> +          <Route index element={<SubjectCreateForm />} />
이건 지우님이 수정해주셔야 할 거 같습니다!
지우님이 컴포넌트로 만들어주셔서 일단 확인 차 넣은거라서용

2024-10-30 07:05 UTC, JUYOUNG0728 commented on public/index.html
> +    <meta property="og:image" content="../src/assets/images/logo.svg" />
학수님께서 리뷰 주신 내용 모두 수정했습니다!

2024-10-30 07:05 UTC, JUYOUNG0728 commented on src/assets/images/messages.png
이건 처음 알았네요! 같은 이미지인데 색상 값만 바꿔서 여러 군데 사용해야 할 때 유용할 거 같아요

2024-10-30 07:06 UTC, Jiwoo11111 commented on src/Main.jsx
> +          <Route index element={<SubjectCreateForm />} />
그럼 이 부분은 제가 이번 pr부분에서 수정해서 올릴게요!! 홈페이지에 컴포넌트 넣는 방식으로 하겠습니당

2024-10-30 07:07 UTC, haksoo0918 approved these changes
수정도 빠르시군요. 😄

2024-10-30 07:07 UTC, haksoo0918 commented on src/Main.jsx
> +          <Route index element={<SubjectCreateForm />} />
아 테스트였군요. 이해했습니다. :)

2024-10-30 07:08 UTC, JUYOUNG0728 commented on src/Main.jsx
> +          <Route index element={<SubjectCreateForm />} />
넵 디자인까지 같이 들어가실 때 수정해주시면 될 거 같습니당! 감사합니다 :D

2024-10-30 07:08 UTC, merged